#!/usr/bin/env node
/**
 * Agentic QE v3 Statusline (minimal fallback, generated by aqe init)
 * For the full statusline, reinstall: npx agentic-qe init --auto
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

function q(bin, args, d) { try { return execFileSync(bin, args, { encoding: 'utf-8', timeout: 3000, stdio: ['pipe', 'pipe', 'pipe'] }).trim(); } catch { return d || ''; } }

const dir = path.resolve(__dirname, '..', '..');
const dbPath = path.join(dir, '.agentic-qe', 'memory.db');
let patterns = 0;
try {
  if (fs.existsSync(dbPath)) {
    const Database = require('better-sqlite3');
    const db = new Database(dbPath, { readonly: true, fileMustExist: true });
    db.pragma('busy_timeout = 5000');
    patterns = db.prepare("SELECT COUNT(*) AS c FROM qe_patterns WHERE usage_count > 0 OR quality_score > 0 OR name NOT LIKE 'bench-%'").get()?.c || 0;
    db.close();
  }
} catch { /* ignore */ }

const branch = q('git', ['branch', '--show-current']);
const branchStr = branch ? `  \x1b[34m⎇ ${branch}\x1b[0m` : '';
const patStr = patterns > 0 ? `  \x1b[35m🎓 ${patterns} patterns\x1b[0m` : '';

console.log(`\x1b[1m\x1b[35m▊ Agentic QE v3\x1b[0m${branchStr}${patStr}`);
