import { StyleSheet } from "react-native";
import { colors } from "../../../utils/colors";

export const styles = StyleSheet.create({
  cardContainer: {
    padding: 8,
    height: 140,
    borderRadius: 10,
    backgroundColor: "#ffffff",
    shadowColor: "#d2d2d2",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,

    elevation: 7,
    marginVertical: 6.5,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardVotesContainer: {
    flex: 1,
    height: 35,
    marginLeft: 10,
    borderRadius: 4,
    alignItems: "center",
    flexDirection: "row",
  },
  cardVotesText: {
    fontFamily: "Poppins_400Regular",
    fontSize: 14,
    fontWeight: "500",
    fontStyle: "normal",
    lineHeight: 21,
    letterSpacing: 0,
    // textAlign: "center",
    color: "#ffffff",
  },
  errorText: {
    color: "red",
    paddingLeft: 15,
    marginBottom: 10,
  },
  cardIdContainer: {
    width: 77,
    height: 36,
    borderRadius: 4,
    backgroundColor: "#cceadf",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: 3,
    paddingRight: 11,
  },
  cardIdText: {
    fontFamily: "Poppins_500Medium",
    fontSize: 12,
    letterSpacing: 0,
    textAlign: "left",
    color: "#3ba580",
  },
  cardNameText: {
    fontFamily: "Poppins_700Bold",
    fontSize: 13,
    letterSpacing: 0,
    textAlign: "left",
    color: "#707070",
  },
  cardCompletionContainer: {
    width: 36,
    height: 36,
    borderRadius: 4,
    backgroundColor: "#24c38b",
    justifyContent: "center",
    alignItems: "center",
  },
  cardCompletionText: {
    fontFamily: "Poppins_700Bold",
    fontSize: 15,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: "#ffffff",
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  statusContainer: {
    width: 73,
    height: 16,
    borderRadius: 18,
    backgroundColor: "#24c38b",
    alignItems: "center",
    justifyContent: "center",
  },
  statusText: {
    fontFamily: "Poppins_700Bold",
    fontSize: 7,
    lineHeight: 10,
    letterSpacing: 0,
    textAlign: "left",
    color: "#ffffff",
  },
  cardDateContainer: {
    width: 155,
    height: 35,
    borderRadius: 4,
    backgroundColor: "#f7f7f7",
    alignItems: "center",
    flexDirection: "row",
  },
  cardDateText: {
    fontFamily: "Poppins_500Medium",
    fontSize: 14,
    fontWeight: "500",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: "white",
  },
  footerTitle: {
    fontFamily: "Poppins_700Bold",
    fontSize: 7,
    fontWeight: "bold",
    fontStyle: "normal",
    lineHeight: 10,
    letterSpacing: 0,
    textAlign: "left",
    color: "#707070",
    marginBottom: 5,
  },
  fab: {
    position: "absolute",
    margin: 16,
    right: 0,
    bottom: 0,
    backgroundColor: "#24c38b",
  },
  greenButtonStyle: {
    width: "50%",
    alignSelf: "center",
    height: 36,
    borderRadius: 7,
    marginBottom: 10,
  },
  greenButtonText: {
    fontFamily: "Poppins_500Medium",
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0,
    textAlign: "right",
    color: "#ffffff",
  },
  modalContainerStyle: {
    backgroundColor: "white",
    borderRadius: 10,
    padding: 20,
  },
  modalTitle: {
    color: colors.primary,
    fontWeight: "bold",
    fontSize: 25,
  },
  modalFieldTitle: {
    fontFamily: "Poppins_400Regular",
    fontSize: 14,
    lineHeight: 16,
    color: "#707070",
    marginTop: 10,
  },
  modalInput: {
    borderColor: colors.disabled,
    padding: 5,
    marginBottom: 10,
    borderWidth: 1,
    borderRadius: 7,
    fontFamily: "Poppins_400Regular",
    fontSize: 14,
    lineHeight: 16,
    color: "#707070",
    marginTop: 10,
  },
});
