import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  title: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 17,
    fontWeight: 'bold',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
  },
  container: {
    marginTop: 23,
    width: '100%',
    height: 90,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    shadowColor: 'rgba(0, 0, 0, 0.05)',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 15,
    shadowOpacity: 1,
    padding: 17,
  },
  infoContainer: {
    flex: 1,
    width: '100%',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    shadowColor: 'rgba(0, 0, 0, 0.05)',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 15,
    shadowOpacity: 1,
    // marginHorizontal: 23,
    padding: 18,
  },
  collapsibleTrigger: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
  },
  collapsibleContent: {
    borderRadius: 10,
    padding: 14,
    marginTop: 5,
    backgroundColor: '#ffffff',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#f7f7f7',
  },
  collapsibleTextArea: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 15,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
  },
  subtitle: {
    fontFamily: 'Poppins_700Bold',
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
    fontSize: 13,
    marginVertical: 5,
    marginBottom: 5,
  },
  text: {
    fontFamily: 'Poppins_400Regular',
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 15,
    fontSize: 12,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
  },
  stepText: {
    marginVertical: 5,
    fontSize: 29,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: '#24c38b',
  },
  stepSubtitle: {
    fontFamily: 'Poppins_700Bold',
    marginVertical: 5,
    fontSize: 17,
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
  },
  stepDescription: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 15,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
  },
  stepNote: {
    fontFamily: 'Poppins_400Regular',
    marginVertical: 5,
    fontSize: 10,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 14,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
  },
  radioLabel: {
    fontFamily: 'Poppins_400Regular',
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
  },
  grmInput: {
    // height: 40,
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    letterSpacing: 0,
    // textAlign: "left",
    color: '#707070',
  },

  // dropdown
  dropdownWrapper: {
    marginHorizontal: 50,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  dropdownText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
  },
  dropdownLabel: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
  },
  dropdownContainer: {
    borderColor: '#dedede',
    elevation: 3,
  },
  dropdownStyle: {
    borderColor: '#dedede',
    elevation: 3,
  },
  audioText: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 18,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#707070',
    marginVertical: 13,
  },
  attachmentImage: {
    height: 120,
    width: '100%',
    borderRadius: 8,
  },
  imageContainer: {
    position: 'relative',
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#f8f9fa',
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  imageOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 20,
  },
  expandIcon: {
    margin: 0,
  },
  unknownFileContainer: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e9ecef',
    marginBottom: 8,
  },
  unknownFileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  unknownFileHint: {
    fontSize: 11,
    color: '#6c757d',
    fontStyle: 'italic',
    marginLeft: 32,
  },
  // Attachment list styles
  attachmentsSection: {
    marginVertical: 8,
  },
  attachmentsList: {
    width: '100%',
  },
  attachmentTypeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
    marginTop: 8,
    marginBottom: 4,
  },
  attachmentTypeTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#495057',
    marginLeft: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  attachmentItem: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e9ecef',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  attachmentItemPlaying: {
    backgroundColor: '#e3f2fd',
    borderColor: '#2196f3',
    borderWidth: 2,
  },
  attachmentItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    minHeight: 48,
  },
  fileIcon: {
    marginRight: 12,
  },
  fileName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    color: '#343a40',
    marginRight: 12,
  },
  fileNamePlaying: {
    color: '#2196f3',
    fontWeight: '600',
  },
  fileTypeIndicator: {
    backgroundColor: '#f8f9fa',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 12,
  },
  fileTypeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#6c757d',
    textTransform: 'uppercase',
  },
  audioControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minWidth: 120,
  },
  soundWaveContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
  },
  soundWave: {
    width: 3,
    backgroundColor: '#2196f3',
    marginHorizontal: 1,
    borderRadius: 1.5,
  },
  soundWave1: {
    height: 8,
    animationDuration: '0.5s',
  },
  soundWave2: {
    height: 12,
    animationDuration: '0.7s',
  },
  soundWave3: {
    height: 10,
    animationDuration: '0.6s',
  },
  soundWave4: {
    height: 6,
    animationDuration: '0.8s',
  },
  audioTimer: {
    fontSize: 10,
    fontWeight: '600',
    color: '#2196f3',
    minWidth: 80,
    textAlign: 'right',
  },
  actionButtonActive: {
    backgroundColor: '#dc3545',
  },
  actionButtonSecondary: {
    backgroundColor: '#6c757d',
  },
  actionButtonText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
  },
  expandedPlayerContainer: {
    borderTopWidth: 1,
    borderTopColor: '#e9ecef',
    padding: 8,
    backgroundColor: '#ffffff',
    zIndex: 1000,
    elevation: 15,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    marginHorizontal: -1,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
});
