
auth.token=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

defaults.org=freddy-r-p
defaults.project=react-native

defaults.url=https://sentry.io/
