import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'grm_issues',
      columns: [
        { name: 'project', type: 'string', isIndexed: true },
        { name: 'issue_date', type: 'number' },
        { name: 'intake_date', type: 'number' },
        { name: 'category', type: 'string', isIndexed: true },
        { name: 'issue_type', type: 'string', isIndexed: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'tracking_code', type: 'string', isOptional: true },
        { name: 'description', type: 'string' },
        { name: 'issue_location', type: 'string', isOptional: true },
        { name: 'citizen_type', type: 'string' },
        { name: 'citizen', type: 'string', isOptional: true },
        { name: 'citizen_confidential', type: 'string', isOptional: true },
        { name: 'gender', type: 'string', isOptional: true },
        { name: 'contact_medium', type: 'string' },
        { name: 'contact_info_type', type: 'string', isOptional: true },
        { name: 'contact_information', type: 'string', isOptional: true },
        { name: 'contact_info_confidential', type: 'string', isOptional: true },
        { name: 'citizen_age_group', type: 'string', isOptional: true, isIndexed: true },
        { name: 'citizen_group_1', type: 'string', isOptional: true, isIndexed: true },
        { name: 'citizen_group_2', type: 'string', isOptional: true, isIndexed: true },
        { name: 'reporter', type: 'string', isIndexed: true },
        { name: 'assignee', type: 'string', isOptional: true, isIndexed: true },
        { name: 'administrative_region', type: 'string', isIndexed: true },
        { name: 'resolution_days', type: 'number', isOptional: true },
        { name: 'resolution_date', type: 'number', isOptional: true },
        { name: 'resolution_accepted', type: 'string', isOptional: true },
        { name: 'rating', type: 'number', isOptional: true },
        { name: 'escalate_flag', type: 'boolean', isOptional: true },
        { name: 'confirmed', type: 'boolean', isOptional: true },
        { name: 'amended_from', type: 'string', isOptional: true, isIndexed: true },
        { name: 'accepted_date', type: 'number', isOptional: true },
        { name: 'reject_reason', type: 'string', isOptional: true },
        { name: 'rejected_date', type: 'number', isOptional: true },
        { name: 'rejected_by', type: 'string', isOptional: true, isIndexed: true },
        { name: 'escalated_date', type: 'number', isOptional: true },
        { name: 'escalated_by', type: 'string', isOptional: true, isIndexed: true },
        { name: 'escalation_reason', type: 'string', isOptional: true },
        { name: 'resolution_text', type: 'string', isOptional: true },
        { name: 'resolved_by', type: 'string', isOptional: true, isIndexed: true },
        { name: 'rated_date', type: 'number', isOptional: true },
        { name: 'appeal_submitted', type: 'boolean', isOptional: true },
        { name: 'appeal_date', type: 'number', isOptional: true },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_projects',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'project_code', type: 'string', isIndexed: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'start_date', type: 'number', isOptional: true },
        { name: 'end_date', type: 'number', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'logo', type: 'string', isOptional: true },
        { name: 'default_language', type: 'string', isOptional: true },
        { name: 'auto_escalation_days', type: 'number', isOptional: true },
        { name: 'enable_citizen_feedback', type: 'boolean' },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_issue_age_groups',
      columns: [
        { name: 'age_group', type: 'string' },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_issue_attachments',
      columns: [
        { name: 'grm_issue', type: 'string', isIndexed: true },
        { name: 'attachment', type: 'string' },
        { name: 'file_name', type: 'string', isOptional: true },
        { name: 'local_url', type: 'string', isOptional: true },
        { name: 'uploaded', type: 'boolean' },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_issue_categories',
      columns: [
        { name: 'category_name', type: 'string' },
        { name: 'label', type: 'string' },
        { name: 'abbreviation', type: 'string' },
        { name: 'assigned_department', type: 'string', isIndexed: true },
        { name: 'assigned_appeal_department', type: 'string', isOptional: true, isIndexed: true },
        {
          name: 'assigned_escalation_department',
          type: 'string',
          isOptional: true,
          isIndexed: true,
        },
        { name: 'confidentiality_level', type: 'string' },
        { name: 'redirection_protocol', type: 'string' },
        { name: 'administrative_level', type: 'string', isOptional: true, isIndexed: true },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_issue_citizen_groups',
      columns: [
        { name: 'group_name', type: 'string' },
        { name: 'group_type', type: 'string' },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_issue_departments',
      columns: [
        { name: 'department_name', type: 'string' },
        { name: 'head', type: 'string', isOptional: true, isIndexed: true },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_issue_types',
      columns: [
        { name: 'type_name', type: 'string' },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_issue_statuses',
      columns: [
        { name: 'status_name', type: 'string' },
        { name: 'final_status', type: 'boolean' },
        { name: 'initial_status', type: 'boolean' },
        { name: 'rejected_status', type: 'boolean' },
        { name: 'open_status', type: 'boolean' },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_administrative_regions',
      columns: [
        { name: 'region_name', type: 'string' },
        { name: 'administrative_level', type: 'string', isIndexed: true },
        { name: 'parent_region', type: 'string', isOptional: true, isIndexed: true },
        { name: 'location', type: 'string', isOptional: true },
        { name: 'project', type: 'string', isIndexed: true },
        { name: 'path', type: 'string', isOptional: true },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_issue_comments',
      columns: [
        { name: 'grm_issue', type: 'string', isIndexed: true },
        { name: 'user', type: 'string', isIndexed: true },
        { name: 'comment', type: 'string' },
        { name: 'activity_type', type: 'string', isOptional: true },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_issue_escalation_reasons',
      columns: [
        { name: 'grm_issue', type: 'string', isIndexed: true },
        { name: 'user', type: 'string', isIndexed: true },
        { name: 'comment', type: 'string' },
        { name: 'due_at', type: 'number' },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_issue_logs',
      columns: [
        { name: 'grm_issue', type: 'string', isIndexed: true },
        { name: 'text', type: 'string' },
        { name: 'user', type: 'string', isIndexed: true },
        { name: 'timestamp', type: 'number' },
        { name: 'action_taken', type: 'string', isOptional: true },
        { name: 'action_taken_date', type: 'number', isOptional: true },
        { name: 'action_taken_by', type: 'string', isOptional: true, isIndexed: true },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_project_links',
      columns: [
        { name: 'project', type: 'string', isIndexed: true },
        { name: 'parent', type: 'string' },
        { name: 'parenttype', type: 'string' },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grm_administrative_level_types',
      columns: [
        { name: 'level_name', type: 'string' },
        { name: 'level_order', type: 'number' },
        { name: 'project', type: 'string', isIndexed: true },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'users',
      columns: [
        { name: 'username', type: 'string', isIndexed: true },
        { name: 'email', type: 'string', isIndexed: true },
        { name: 'full_name', type: 'string' },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'user_context',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'context_data', type: 'string' },
        { name: 'creation', type: 'number' },
        { name: 'modified', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
