import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  cardContainer: {
    padding: 8,
    height: 120,
    borderRadius: 10,
    backgroundColor: "#ffffff",
    shadowColor: "#acacac",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,

    elevation: 7,
    marginVertical: 6.5,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardIdContainer: {
    width: 36,
    height: 36,
    borderRadius: 4,
    backgroundColor: "#f7f7f7",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 13,
  },
  cardIdText: {
    fontFamily: "Poppins_700Bold",
    fontSize: 24,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: "#707070",
  },
  cardNameText: {
    fontFamily: "Poppins_700Bold",
    fontSize: 13,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: "#707070",
  },
  cardCompletionContainer: {
    width: 36,
    height: 36,
    borderRadius: 4,
    backgroundColor: "#24c38b",
    justifyContent: "center",
    alignItems: "center",
  },
  cardCompletionText: {
    fontFamily: "Poppins_700Bold",
    fontSize: 15,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: "#ffffff",
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 20,
  },
  cardDateContainer: {
    width: 155,
    height: 35,
    borderRadius: 4,
    backgroundColor: "#f7f7f7",
    alignItems: "center",
    flexDirection: "row",
  },
  cardDateText: {
    fontFamily: "Poppins_500Medium",
    fontSize: 10,
    fontWeight: "500",
    fontStyle: "normal",
    lineHeight: 14,
    letterSpacing: 0,
    textAlign: "left",
    color: "#707070",
  },
});
