import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  cardContainer: {
    padding: 8,
    height: 120,
    borderRadius: 10,
    backgroundColor: "#ffffff",
    shadowColor: "#d2d2d2",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,

    elevation: 7,
    marginVertical: 6.5,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardIdContainer: {
    width: 77,
    height: 36,
    borderRadius: 4,
    backgroundColor: "#cceadf",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: 3,
    paddingRight: 11,
  },
  cardIdText: {
    fontFamily: "Poppins_500Medium",
    fontSize: 12,
    letterSpacing: 0,
    textAlign: "left",
    color: "#3ba580",
  },
  cardNameText: {
    fontFamily: "Poppins_700Bold",
    fontSize: 13,
    letterSpacing: 0,
    textAlign: "left",
    color: "#707070",
  },
  cardCompletionContainer: {
    width: 36,
    height: 36,
    borderRadius: 4,
    backgroundColor: "#24c38b",
    justifyContent: "center",
    alignItems: "center",
  },
  cardCompletionText: {
    fontFamily: "Poppins_700Bold",
    fontSize: 15,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    textAlign: "left",
    color: "#ffffff",
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  statusContainer: {
    width: 73,
    height: 16,
    borderRadius: 18,
    backgroundColor: "#24c38b",
    alignItems: "center",
    justifyContent: "center",
  },
  statusText: {
    fontFamily: "Poppins_700Bold",
    fontSize: 7,
    lineHeight: 10,
    letterSpacing: 0,
    textAlign: "left",
    color: "#ffffff",
  },
  cardDateContainer: {
    width: "100%",
    paddingRight: 10,
    height: 35,
    borderRadius: 4,
    backgroundColor: "#f7f7f7",
    alignItems: "center",
    flexDirection: "row",
  },
  cardDateText: {
    fontFamily: "Poppins_500Medium",
    fontSize: 10,
    fontWeight: "500",
    fontStyle: "normal",
    lineHeight: 14,
    letterSpacing: 0,
    textAlign: "left",
    color: "#707070",
  },
  footerTitle: {
    fontFamily: "Poppins_700Bold",
    fontSize: 7,
    fontWeight: "bold",
    fontStyle: "normal",
    lineHeight: 10,
    letterSpacing: 0,
    textAlign: "left",
    color: "#707070",
    marginBottom: 5,
  },
  fab: {
    position: "absolute",
    margin: 16,
    right: 0,
    bottom: 0,
    backgroundColor: "#24c38b",
  },
});
