import { Schema } from "../../repositories/local/BaseLocalRepository";
export const issue: Schema = {
  id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
  administrative_region: 'TEXT',
  assignee: 'TEXT',
  category: 'TEXT',
  citizen: 'TEXT',
  contact_information: 'TEXT NULL',
  confirmed: 'BOOLEAN DEFAULT FALSE',
  contact_medium: 'TEXT',
  contact_method: 'TEXT',
  component: 'TEXT',
  created_date: 'DATETIME DEFAULT CURRENT_TIMESTAMP',
  deleted_date: 'DATETIME NULL',
  description: 'TEXT',
  escalated_date: 'DATETIME NULL',
  escalate_flag: 'BOOLEAN DEFAULT FALSE',
  intake_date: 'DATETIME DEFAULT CURRENT_TIMESTAMP NULL',
  issue_date: 'DATETIME NULL',
  issue_location: 'TEXT',
  issue_type: 'TEXT NULL',
  issue_sub_type: 'TEXT NULL',
  location_description: 'TEXT NULL',
  ongoing_issue: 'BOOLEAN DEFAULT FALSE',
  reporter: 'TEXT',
  resolution_date: 'DATETIME NULL',
  status: 'TEXT NULL',
  sub_component: 'TEXT NULL',
  title: 'TEXT NULL',
  tracking_code: 'TEXT',
  internal_code: 'TEXT',
  updated_date: 'DATETIME NULL',
  sync_date: 'DATETIME NULL',
}


