import React, { useState, useEffect } from 'react';
import {
  View,
  ScrollView,
  Text,
  Platform,
  KeyboardAvoidingView,
  TextInput as NativeTextInput} from 'react-native';
import { useNavigation } from '@react-navigation/native';
import DateTimePickerModal from 'react-native-modal-datetime-picker';
import { Button, Checkbox, Dialog, Paragraph, Portal, TextInput } from 'react-native-paper';
import * as ImagePicker from 'expo-image-picker';
import * as ImageManipulator from 'expo-image-manipulator';
import moment from 'moment';
import { i18n } from "../../../../translations/i18n";
import CustomDropDownPicker from '../../../../components/CustomDropDownPicker/CustomDropDownPicker';
import { colors } from '../../../../utils/colors';
import { styles } from './Content.styles';
import AddAttachmentCard from "../../GRM/components/AddAttachmentCard";
import { showToast } from '../../../../utils/utils';

const theme = {
  roundness: 12,
  colors: {
    ...colors,
    background: 'white',
    placeholder: '#dedede',
    text: '#707070',
  },
};

/**
 * Renders the content for the Citizen Report Step 2 screen, allowing users to select issue details such as categories, types
 * sub types, components, sub components, attach media, and provide additional information before proceeding to the next step.
 *
 * @component
 * @param {Object} props
 * @param {Object} props.stepOneParams - Parameters from the previous step.
 * @param {Array<Object>} props.issueCategories - List of issue categories.
 * @param {Array<Object>} props.issueTypes - List of issue types.
 * @param {Array<Object>} props.issueSubTypes - List of issue sub-types.
 * @param {Array<Object>} props.issueComponents - List of issue components.
 * @param {Array<Object>} props.issueSubComponents - List of issue sub-components.
 *
 * @returns {React.ReactElement} The rendered component.
 */

function Content({ stepOneParams, issueCategories, issueTypes, issueSubTypes, issueComponents, issueSubComponents }: { stepOneParams: object; issueCategories: Array<object>; issueTypes: Array<object>; issueSubTypes: Array<object>; issueComponents: Array<object>; issueSubComponents: Array<object>; }): React.ReactElement {
  const navigation = useNavigation();

  //Picker autogenerated values
  const [pickerType, setPickerType] = useState(null);
  const [pickerCategory, setPickerCategory] = useState(null);
  const [pickerSubType, setPickerSubType] = useState(null);
  const [pickerComponent, setPickerComponent] = useState(null);
  const [pickerSubComponent, setPickerSubComponent] = useState(null);

  // Non-filtered sets of items
  const [types, setTypes] = useState(issueTypes ?? []);
  const [categories, setCategories] = useState(issueCategories ?? []);
  const [subTypes, setSubTypes] = useState(issueSubTypes ?? []);
  const [components, setComponents] = useState(issueComponents ?? []);
  const [subComponents, setSubComponents] = useState(issueSubComponents ?? []);

  // Filtered subsequent dropdown items based on its parent picker
  const [filteredSubComponents, setFilteredSubComponents] = useState([]);
  const [filteredSubTypes, setFilteredSubTypes] = useState([]);

  // Complete selected value
  const [selectedIssueType, setSelectedIssueType] = useState(null);
  const [selectedIssueSubType, setSelectedIssueSubType] = useState(null);
  const [selectedIssueComponent, setSelectedIssueComponent] = useState(null);
  const [selectedIssueSubComponent, setSelectedIssueSubComponent] = useState(null);

  //Other
  const [checked, setChecked] = useState(false);
  const [additionalDetails, setAdditionalDetails] = useState(null);
  const [additionalDetailsError, setAdditionalDetailsError] = useState(null);
  const [date, setDate] = useState(null);
  const [attachment, setAttachment] = useState({});
  const [recordingURI, setRecordingURI] = useState();
  const [isDatePickerVisible, setDatePickerVisibility] = useState(false);
  const [showDialog, setShowDialog] = useState(false);

  const _hideDialog = () => setShowDialog(false);
  const _showDialog = () => setShowDialog(true);

  useEffect(() => {
    if (issueTypes) {
      setTypes(issueTypes);
    }
    if (issueCategories) {
      setCategories(issueCategories);
    }
    if (issueSubTypes) {
      setSubTypes(issueSubTypes);
    }
    if (issueComponents) {
      setComponents(issueComponents);
    }
    if (issueSubComponents) {
      setSubComponents(issueSubComponents);
    }
  }, [issueTypes, issueCategories, issueSubTypes, issueComponents, issueSubComponents]);

  useEffect(() => {
    (async () => {
      if (Platform.OS !== 'web') {
        const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
        if (status !== 'granted') {
          alert('Sorry, we need camera roll permissions to make this work!');
        }
      }
    })();
  }, []);

  const showDatePicker = () => {
    setDatePickerVisibility(true);
  };

  const hideDatePicker = () => {
    setDatePickerVisibility(false);
  };

  const handleConfirm = (_date) => {
    setDate(_date);
    hideDatePicker();
  };

  const getCategory = (value) => {
    const result = issueCategories.filter((obj) => obj.name === value);
    const first = result?.[0];
    const _category = first
      ? {
        id: first.id,
        name: first.name,
        confidentiality_level: first.confidentiality_level,
        assigned_department: first.assigned_department?.id ?? null,
        administrative_level: first.assigned_department?.administrative_level ?? null,
      }
      : null;
    return _category;
  };

  const filterSubTypes = () => {
    if (!selectedIssueType) return [];

    // Rename 'parent' key from objects to 'parentType' to prevent key conflicts in dropdown library
    const renamedSubTypes = subTypes.map(({ parent, ...rest }) => ({
      ...rest,
      parentType: parent,
    }));
    
    return renamedSubTypes.filter((obj) => {
      if (!obj?.parentType || !selectedIssueType?.id) return false;
      return String(obj.parentType.id) === String(selectedIssueType.id);
    });
  };

  useEffect(() => {
    setFilteredSubTypes(selectedIssueType ? filterSubTypes() : []);
    setPickerSubType(null);
  }, [selectedIssueType, subTypes]);


  const pickImage = async () => {
    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: true,
      // aspect: [4, 3],
      quality: 1,
    });

    if (
      !result.canceled &&
      (result.localUri || (result.assets.length > 0 && result.assets[0].uri))
    ) {
      const manipResult = await ImageManipulator.manipulateAsync(
        result.localUri || result.assets[0].uri,
        [{ resize: { width: 1000, height: 1000 } }],
        { compress: 1, format: ImageManipulator.SaveFormat.PNG }
      );
      setAttachment({ ...manipResult, id: new Date() });
    }
  };
  const openCamera = async () => {
    const result = await ImagePicker.launchCameraAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: true,
      aspect: [4, 3],
      quality: 1,
    });

    if (
      !result.canceled &&
      (result.localUri || (result.assets.length > 0 && result.assets[0].uri))
    ) {
      const manipResult = await ImageManipulator.manipulateAsync(
        result.localUri || result.assets[0].uri,
        [{ resize: { width: 1000, height: 1000 } }],
        { compress: 1, format: ImageManipulator.SaveFormat.PNG }
      );
      setAttachment({ ...manipResult, id: new Date() });
    }
  };

  useEffect(() => {
    (async () => {
      if (Platform.OS !== 'web') {
        const { status } = await ImagePicker.requestCameraPermissionsAsync();
        if (status !== 'granted') {
          alert('Sorry, we need camera roll permissions to make this work!');
        }
      }
    })();
  }, []);

  const filterSubComponents = () => {
    if (!selectedIssueComponent) return [];

    // Rename 'parent' key from objects to 'parentComponent' to prevent key conflicts in dropdown library
    const renamedSubComponents = subComponents.map(({ parent, ...rest }) => ({
      ...rest,
      parentComponent: parent,
    }));
    return renamedSubComponents.filter(
      (obj) => {
         if (!obj?.parentComponent || !selectedIssueComponent?.id) return false;
         return String(obj.parentComponent.id) === String(selectedIssueComponent.id);
      }
    );
  };

  useEffect(() => {
    setFilteredSubComponents(selectedIssueComponent ? filterSubComponents() : []);
    setPickerSubComponent(null); 
  }, [selectedIssueComponent, subComponents]);

  const onNext = () => {
    navigation.navigate('CitizenReportLocationStep', {
      stepOneParams,
      stepTwoParams: {
        date: date ? date.toISOString() : undefined,
        issueType: selectedIssueType ?? null,
        issueSubType: selectedIssueSubType ?? null,
        issueComponent: selectedIssueComponent ?? null,
        issueSubComponent: selectedIssueSubComponent ?? null,
        ongoingEvent: checked,
        attachment: attachment.uri
          ? {
              url: '',
              id: attachment?.id,
              uploaded: false,
              local_url: attachment?.uri,
              name: attachment?.uri.split('/').pop(),
            }
          : undefined,
        recording: recordingURI
          ? {
              url: '',
              id: recordingURI.split('/').pop(),
              uploaded: false,
              local_url: recordingURI,
              isAudio: true,
              name: recordingURI.split('/').pop(),
            }
          : undefined,
        category: pickerCategory ? getCategory(pickerCategory) : null,
        additionalDetails,
      },
    });
  };

  return (
    <ScrollView>
      <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : null}>
        <View style={{ padding: 23 }}>
          <Text style={styles.stepText}>{i18n.t('step_3')}</Text>
          <Text style={styles.stepDescription}>{i18n.t('step_2_subtitle')}</Text>
          <Text style={styles.stepNote}>{i18n.t('step_2_explanation')}</Text>
        </View>
        <View
          style={{
            flexDirection: 'row',
            paddingHorizontal: 23,
            paddingBottom: 10,
            justifyContent: 'space-between',
          }}
        >
          <Button
            theme={{ ...theme, colors: { ...theme.colors, primary: 'white' } }}
            icon="calendar"
            compact
            style={{
              shadowColor: '#000',
              shadowOffset: {
                width: 0,
                height: 2,
              },
              shadowOpacity: 0.25,
              shadowRadius: 3.84,
              elevation: 3,
              flex: 1,
              marginHorizontal: 10,
            }}
            uppercase={false}
            labelStyle={{
              color: colors.primary,
              fontFamily: 'Poppins_400Regular',
              fontSize: 13,
            }}
            mode="contained"
            onPress={showDatePicker}
          >
            {date ? moment(date).format('DD-MMMM-YY') : i18n.t('step_2_select_date')}
          </Button>
          <Button
            compact
            theme={theme}
            labelStyle={{
              color: 'white',
              fontFamily: 'Poppins_400Regular',
              fontSize: 12,
            }}
            mode="contained"
            uppercase={false}
            onPress={() => setDate(new Date())}
          >
            {i18n.t('step_2_set_today')}
          </Button>
        </View>
        <View
          style={{
            flexDirection: 'row',
            paddingHorizontal: 43,
            paddingBottom: 10,
            alignItems: 'center',
          }}
        >
          <Checkbox.Android
            color={colors.primary}
            status={checked ? 'checked' : 'unchecked'}
            onPress={() => {
              setChecked(!checked);
            }}
          />
          <Text style={[styles.stepNote, { flex: 1 }]}>{i18n.t('step_2_ongoing_hint')}</Text>
        </View>
        <View
          style={{
            flexDirection: 'row',
            paddingHorizontal: 23,
            marginBottom: 35,
            justifyContent: 'space-between',
          }}
        >
          <View style={{ flex: 2 }} />
        </View>
        <DateTimePickerModal
          isVisible={isDatePickerVisible}
          mode="date"
          maximumDate={new Date()}
          onConfirm={handleConfirm}
          onCancel={hideDatePicker}
        />
        <View>
          <CustomDropDownPicker
            schema={{
              label: 'name',
              value: 'name',
            }}
            zIndex={3000}
            zIndexInverse={2000}
            placeholder={i18n.t('step_2_placeholder_1')}
            value={pickerType}
            items={types}
            setPickerValue={setPickerType}
            setItems={setTypes}
            onSelectItem={(item) => setSelectedIssueType(item)}
          />
        </View>
        <View style={{ zIndex: 2000 }}>
          <CustomDropDownPicker
            schema={{
              label: 'name',
              value: 'name',
            }}
            zIndex={3000}
            zIndexInverse={2000}
            placeholder={i18n.t('step_2_placeholder_5')}
            value={pickerSubType}
            items={filteredSubTypes}
            setPickerValue={setPickerSubType}
            onSelectItem={(item) =>
              setSelectedIssueSubType({
                ...item,
                parent: item.parentType,
                parentType: undefined, // Restore original parent property by removing the temporary parentType alias
              })
            }
          />
        </View>
        <View style={{ zIndex: 1000 }}>
          <CustomDropDownPicker
            schema={{
              label: 'name',
              value: 'name',
              id: 'id',
              confidentiality_level: 'confidentiality_level',
              assigned_department: 'assigned_department',
            }}
            zIndex={3000}
            zIndexInverse={2000}
            placeholder={i18n.t('step_2_placeholder_2')}
            value={pickerCategory}
            items={categories}
            setPickerValue={setPickerCategory}
          />
        </View>
        <View>
          <CustomDropDownPicker
            schema={{
              label: 'name',
              value: 'name',
            }}
            zIndex={3000}
            zIndexInverse={2000}
            placeholder={i18n.t('step_2_placeholder_6')}
            value={pickerComponent}
            items={components}
            setPickerValue={setPickerComponent}
            setItems={setComponents}
            onSelectItem={(item) => setSelectedIssueComponent(item)}
          />
        </View>
        <View>
          <CustomDropDownPicker
            schema={{
              label: 'name',
              value: 'name',
            }}
            zIndex={3000}
            zIndexInverse={2000}
            placeholder={i18n.t('step_2_placeholder_7')}
            value={pickerSubComponent}
            items={filteredSubComponents}
            setPickerValue={setPickerSubComponent}
            onSelectItem={(item) =>
              setSelectedIssueSubComponent({
                ...item,
                parent: item.parentComponent,
                parentComponent: undefined, // Restore original parent property by removing the temporary parentComponent alias
              })
            }
          />
        </View>

        <View style={{ paddingHorizontal: 50 }}>
          <TextInput
            multiline
            numberOfLines={4}
            style={[
              styles.grmInput,
              {
                height: 100,
                justifyContent: 'flex-start',
                textAlignVertical: 'top',
                fontSize: 14,
              },
            ]}
            placeholder={i18n.t('step_2_placeholder_3')}
            outlineColor="#dedede"
            theme={theme}
            mode="outlined"
            error={!!additionalDetailsError}
            value={additionalDetails}
            onChangeText={(text) => {
              setAdditionalDetailsError(null)
              setAdditionalDetails(text)
            }}
            render={(innerProps) => (
              <NativeTextInput
                {...innerProps}
                style={[
                  innerProps.style,
                  {
                    paddingTop: 8,
                    paddingBottom: 8,
                    height: 100,
                  },
                ]}
              />
            )}
          />
        </View>
        <View style={{ paddingHorizontal: 50 }}>
          <Text
            style={{
              fontFamily: 'Poppins_400Regular',
              fontSize: 12,
              fontWeight: 'normal',
              fontStyle: 'normal',
              lineHeight: 18,
              letterSpacing: 0,
              textAlign: 'left',
              color: '#707070',
              marginVertical: 13,
            }}
          >
            {i18n.t('step_2_share_photos')}
          </Text>
          <AddAttachmentCard
            theme={theme}
            onAttachmentChange={(a, r) => {
              setAttachment(a);
              setRecordingURI(r);
            }}
          />
        </View>

        <View style={{ paddingHorizontal: 50 }}>
          <Button
            theme={theme}
            style={{ alignSelf: 'center', margin: 24 }}
            labelStyle={{ color: 'white', fontFamily: 'Poppins_500Medium' }}
            mode="contained"
            onPress={() => {
              if (
                selectedIssueType === null ||
                selectedIssueSubType === null ||
                pickerCategory === null ||
                !additionalDetails
              ) {
                if (!additionalDetails) {
                  setAdditionalDetailsError('This field is required');
                }
                showToast(i18n.t('please_choose_value_for_required_field'));
                return;
              }
              const selectedCategory = getCategory(pickerCategory);
              if (selectedCategory && selectedCategory.confidentiality_level === 'Confidential') {
                _showDialog();
                return;
              }
              onNext();
            }}
          >
            {i18n.t('next')}
          </Button>
        </View>
      </KeyboardAvoidingView>

      <Portal>
        <Dialog visible={showDialog} onDismiss={_hideDialog}>
          <Dialog.Title>{i18n.t('warning')}</Dialog.Title>
          <Dialog.Content>
            <Paragraph>{i18n.t('confidential_complaint')}</Paragraph>
          </Dialog.Content>
          <Dialog.Actions>
            <Button
              theme={theme}
              style={{
                alignSelf: 'center',
                backgroundColor: '#E74C3C',
                paddingLeft: 15,
                paddingRight: 15,
              }}
              labelStyle={{ color: 'white', fontFamily: 'Poppins_500Medium' }}
              mode="contained"
              onPress={_hideDialog}
            >
              {i18n.t('no')}
            </Button>
            <Button
              theme={theme}
              style={{ alignSelf: 'center', margin: 24, paddingLeft: 15, paddingRight: 15 }}
              labelStyle={{ color: 'white', fontFamily: 'Poppins_500Medium' }}
              mode="contained"
              onPress={() => {
                _hideDialog();
                onNext();
              }}
            >
              {i18n.t('yes')}
            </Button>
          </Dialog.Actions>
        </Dialog>
      </Portal>
    </ScrollView>
  );
}

export default Content;
