#!/usr/bin/env node
// AQE v3 Worker Daemon Stop Script (cross-platform)
// Generated by aqe init

const { existsSync, readFileSync, unlinkSync } = require('fs');
const { join } = require('path');

const workersDir = join(__dirname);
const pidFile = join(workersDir, 'daemon.pid');

if (!existsSync(pidFile)) { console.log('No PID file found - daemon may not be running'); process.exit(0); }

const pid = parseInt(readFileSync(pidFile, 'utf-8').trim(), 10);
try {
  process.kill(pid, 0); // Check if alive
  console.log('Stopping daemon (PID: ' + pid + ')...');
  process.kill(pid, 'SIGTERM');
  try { unlinkSync(pidFile); } catch {}
  console.log('Daemon stopped');
} catch {
  console.log('Daemon not running (stale PID file)');
  try { unlinkSync(pidFile); } catch {}
}
